<a href="https://colab.research.google.com/github/AviFeygin/EECS-4080/blob/main/Israpol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
import torch
import scipy
import pandas as pd
import matplotlib.pyplot as plt
import keras as ker
import seaborn as sea
import xlrd as xlr
import numpy as np
import matplotlib.pyplot as plt
import pymc3 as pm
import theano
import statsmodels.api as stm

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

#ignore all warnings
import warnings
warnings.filterwarnings('ignore')
sea.set()

import itertools
!pip install --upgrade xlrd

from google.colab import data_table
data_table.enable_dataframe_formatter()
from vega_datasets import data

verbose = 0

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Downloading Text

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = '/content/drive/MyDrive/Polls.xls'
polls = pd.read_excel(data)
polls_2021 = pd.read_excel(data, sheet_name=0, index_col=0)

In [ ]:
print("polls_2021 shape:")
print(polls_2021.shape)
just_polls = polls_2021.iloc[1:161, 4:25]
print("just polls")
#fixing the float errors
just_polls['Days Before election'] = just_polls['Days Before election'].round().astype('int')
display(just_polls)
number_of_parties = 14
number_of_blocs = 4

polls_2021 shape:
(159, 23)
just polls


Days Before election  Likud  Yesh Atid  Blue & White  \
Date                                                                        
2021-03-20 00:00:02                     3     31         19           4.0   
2021-03-19 00:00:03                     4     30         18           4.0   
2021-03-19 00:00:04                     4     32         18           4.0   
2021-03-19 00:00:05                     4     31         19           4.0   
2021-03-18 00:00:06                     5     30         19           5.0   
...                                   ...    ...        ...           ...   
2020-06-17 00:02:35                   279     41         15          11.0   
2020-06-17 00:02:36                   279     41         15          10.0   
2020-06-11 00:02:37                   285     41         16          13.0   
2020-06-08 00:02:38                   288     40         14          12.0   
2020-05-26 00:02:39                   301     41         14          12.0   

                     Joint List  Shas  UTJ  Yisrael Beiteinu  Meretz  Ra'am  \
Date                                                                          
2021-03-20 00:00:02           8     8    7                 7     4.0    4.0   
2021-03-19 00:00:03           8     8    7                 6     4.0    4.0   
2021-03-19 00:00:04           8     8    7                 7     4.0    4.0   
2021-03-19 00:00:05           8     8    7                 7     4.0    4.0   
2021-03-18 00:00:06           8     8    6                 8     4.0    4.0   
...                         ...   ...  ...               ...     ...    ...   
2020-06-17 00:02:35          16    10    7                 8     5.0    0.0   
2020-06-17 00:02:36          16     9    7                 8     6.0    0.0   
2020-06-11 00:02:37          15     9    8                 7     5.0    0.0   
2020-06-08 00:02:38          15     9    7                 9     6.0    0.0   
2020-05-26 00:02:39          15     9    8                 6     6.0    0.0   

                     Yamina  New Hope  Labor  Religious Zionist   NEP  \
Date                                                                    
2021-03-20 00:00:02       9         9   5.00               5.00  1.68   
2021-03-19 00:00:03      10        10   6.00               5.00  0.00   
2021-03-19 00:00:04       9         9   6.00               4.00  1.56   
2021-03-19 00:00:05       9         9   5.00               5.00  1.68   
2021-03-18 00:00:06      10         8   5.00               5.00  0.00   
...                     ...       ...    ...                ...   ...   
2020-06-17 00:02:35       7         0   1.32               0.60  0.00   
2020-06-17 00:02:36       8         0   2.76               1.68  0.00   
2020-06-11 00:02:37       6         0   0.00               0.00  0.00   
2020-06-08 00:02:38       8         0   2.28               0.48  0.00   
2020-05-26 00:02:39       9         0   1.80               1.56  0.00   

                     Right Wing  Left Wing  religious  Arab  
Date                                                         
2021-03-20 00:00:02       61.00      28.00         15  16.0  
2021-03-19 00:00:03       61.00      28.00         15  16.0  
2021-03-19 00:00:04       61.00      28.00         15  16.0  
2021-03-19 00:00:05       61.00      28.00         15  16.0  
2021-03-18 00:00:06       61.00      29.00         14  16.0  
...                         ...        ...        ...   ...  
2020-06-17 00:02:35       56.60      27.32         17  21.0  
2020-06-17 00:02:36       58.68      27.76         16  22.0  
2020-06-11 00:02:37       54.00      29.00         17  20.0  
2020-06-08 00:02:38       57.48      28.28         16  21.0  
2020-05-26 00:02:39       57.56      27.80         17  21.0  

[158 rows x 19 columns]

Parties

In [ ]:
likud = just_polls[['Days Before election','Likud']]
#display(likud)
yesh_atid = just_polls[['Days Before election','Yesh Atid']]
blue_and_white = just_polls[['Days Before election','Blue & White']]
joint_list = just_polls[['Days Before election','Joint List']]
shas = just_polls[['Days Before election','Shas']]
utj = just_polls[['Days Before election','UTJ']]
beiteinu = just_polls[['Days Before election','Yisrael Beiteinu']]
meretz = just_polls[['Days Before election','Meretz']]
raam = just_polls[['Days Before election','Ra\'am']]
yamina = just_polls[['Days Before election','Yamina']]
new_hope = just_polls[['Days Before election','New Hope']]
Labor = just_polls[['Days Before election','Labor']]
religious_zionist = just_polls[['Days Before election','Religious Zionist']]


Blocs


In [ ]:
right_wing = just_polls[['Days Before election','Right Wing']]
left_wing = just_polls[['Days Before election','Left Wing']]
religious = just_polls[['Days Before election','religious']]
arab = just_polls[['Days Before election','Arab']]

Defining a LOESS function
it will take in a panda frame column and return the loess column

In [ ]:
#Frame must be a column dataframe with time indexing, delta is an integer that should be the time interval and days which is unique days of the set
#returns new frame with loess and same time indexing
# freame.loc[frame['set_of_numbers'] <= 4, 'equal_or_lower_than_4?'] = 'True' 
# frame.loc[frame['set_of_numbers'] > 4, 'equal_or_lower_than_4?'] = 'False' 
verbose =0
just_polls['Days Before election'].nunique()
def LOESS(frame, delta = 2, days = 1, name = 'Likud'):
  display(frame.shape)
  delta = (delta-1)/2
  length = len(frame.index)
  Loess_frame = pd.DataFrame()
  temp = pd.DataFrame()
  #above_35 = titanic[titanic["Age"] > 35]
  for i in range(3, frame['Days Before election'].max()):
   temp = frame[(frame['Days Before election'] <= (i+delta)) & (frame['Days Before election'] >= (i-delta)) ]
   if len(temp.index)>0:
    x = temp['Days Before election'].values.reshape(-1,1)
 
    y = temp[name].values.reshape(len(temp.index),1)

    if (verbose == 1):
       print("i: ")
       display(i)
       print("y: ")
       display(y)
       print("x: ")
       display(x)


    model = linear_model.LinearRegression().fit(x, y)
    linear_model.LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)
    linear_model.LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)
    display(model.predict([[i]]))
    Loess_frame.append([i, model.predict([[i]])])
    display(Loess_frame)
  return Loess_frame

likud_Loess = LOESS(likud, 3, just_polls['Days Before election'].nunique(), 'Likud')
display(likud_Loess)



(158, 2)

i: 


3

y: 


array([[31],
       [30],
       [32],
       [31]])

x: 


array([[3],
       [4],
       [4],
       [4]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


4

y: 


array([[31],
       [30],
       [32],
       [31],
       [30],
       [32],
       [29]])

x: 


array([[3],
       [4],
       [4],
       [4],
       [5],
       [5],
       [5]])

array([[30.83333333]])

Empty DataFrame
Columns: []
Index: []

i: 


5

y: 


array([[30],
       [32],
       [31],
       [30],
       [32],
       [29]])

x: 


array([[4],
       [4],
       [4],
       [5],
       [5],
       [5]])

array([[30.33333333]])

Empty DataFrame
Columns: []
Index: []

i: 


6

y: 


array([[30],
       [32],
       [29],
       [30]])

x: 


array([[5],
       [5],
       [5],
       [7]])

array([[30.16666667]])

Empty DataFrame
Columns: []
Index: []

i: 


7

y: 


array([[30],
       [28]])

x: 


array([[7],
       [8]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


8

y: 


array([[30],
       [28],
       [28]])

x: 


array([[7],
       [8],
       [9]])

array([[28.66666667]])

Empty DataFrame
Columns: []
Index: []

i: 


9

y: 


array([[28],
       [28]])

x: 


array([[8],
       [9]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


10

y: 


array([[28]])

x: 


array([[9]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


11

y: 


array([[30],
       [27],
       [29]])

x: 


array([[12],
       [12],
       [12]])

array([[28.66666667]])

Empty DataFrame
Columns: []
Index: []

i: 


12

y: 


array([[30],
       [27],
       [29],
       [28]])

x: 


array([[12],
       [12],
       [12],
       [13]])

array([[28.66666667]])

Empty DataFrame
Columns: []
Index: []

i: 


13

y: 


array([[30],
       [27],
       [29],
       [28],
       [29]])

x: 


array([[12],
       [12],
       [12],
       [13],
       [14]])

array([[28.625]])

Empty DataFrame
Columns: []
Index: []

i: 


14

y: 


array([[28],
       [29]])

x: 


array([[13],
       [14]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


15

y: 


array([[29]])

x: 


array([[14]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


18

y: 


array([[29],
       [27],
       [29],
       [29]])

x: 


array([[19],
       [19],
       [19],
       [19]])

array([[28.5]])

Empty DataFrame
Columns: []
Index: []

i: 


19

y: 


array([[29],
       [27],
       [29],
       [29],
       [29]])

x: 


array([[19],
       [19],
       [19],
       [19],
       [20]])

array([[28.5]])

Empty DataFrame
Columns: []
Index: []

i: 


20

y: 


array([[29],
       [27],
       [29],
       [29],
       [29],
       [27],
       [29],
       [28]])

x: 


array([[19],
       [19],
       [19],
       [19],
       [20],
       [21],
       [21],
       [21]])

array([[28.34545455]])

Empty DataFrame
Columns: []
Index: []

i: 


21

y: 


array([[29],
       [27],
       [29],
       [28]])

x: 


array([[20],
       [21],
       [21],
       [21]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


22

y: 


array([[27],
       [29],
       [28],
       [28]])

x: 


array([[21],
       [21],
       [21],
       [23]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


23

y: 


array([[28]])

x: 


array([[23]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


24

y: 


array([[28]])

x: 


array([[23]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


25

y: 


array([[29],
       [27]])

x: 


array([[26],
       [26]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


26

y: 


array([[29],
       [27]])

x: 


array([[26],
       [26]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


27

y: 


array([[29],
       [27],
       [29],
       [28],
       [28]])

x: 


array([[26],
       [26],
       [28],
       [28],
       [28]])

array([[28.16666667]])

Empty DataFrame
Columns: []
Index: []

i: 


28

y: 


array([[29],
       [28],
       [28]])

x: 


array([[28],
       [28],
       [28]])

array([[28.33333333]])

Empty DataFrame
Columns: []
Index: []

i: 


29

y: 


array([[29],
       [28],
       [28]])

x: 


array([[28],
       [28],
       [28]])

array([[28.33333333]])

Empty DataFrame
Columns: []
Index: []

i: 


32

y: 


array([[28]])

x: 


array([[33]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


33

y: 


array([[28]])

x: 


array([[33]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


34

y: 


array([[28],
       [29]])

x: 


array([[33],
       [35]])

array([[28.5]])

Empty DataFrame
Columns: []
Index: []

i: 


35

y: 


array([[29],
       [28]])

x: 


array([[35],
       [36]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


36

y: 


array([[29],
       [28],
       [29]])

x: 


array([[35],
       [36],
       [37]])

array([[28.66666667]])

Empty DataFrame
Columns: []
Index: []

i: 


37

y: 


array([[28],
       [29]])

x: 


array([[36],
       [37]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


38

y: 


array([[29]])

x: 


array([[37]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


39

y: 


array([[29],
       [28]])

x: 


array([[40],
       [40]])

array([[28.5]])

Empty DataFrame
Columns: []
Index: []

i: 


40

y: 


array([[29],
       [28],
       [28]])

x: 


array([[40],
       [40],
       [41]])

array([[28.5]])

Empty DataFrame
Columns: []
Index: []

i: 


41

y: 


array([[29],
       [28],
       [28],
       [29]])

x: 


array([[40],
       [40],
       [41],
       [42]])

array([[28.54545455]])

Empty DataFrame
Columns: []
Index: []

i: 


42

y: 


array([[28],
       [29],
       [31]])

x: 


array([[41],
       [42],
       [43]])

array([[29.33333333]])

Empty DataFrame
Columns: []
Index: []

i: 


43

y: 


array([[29],
       [31],
       [30]])

x: 


array([[42],
       [43],
       [44]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


44

y: 


array([[31],
       [30],
       [31]])

x: 


array([[43],
       [44],
       [45]])

array([[30.66666667]])

Empty DataFrame
Columns: []
Index: []

i: 


45

y: 


array([[30],
       [31],
       [30],
       [29]])

x: 


array([[44],
       [45],
       [46],
       [46]])

array([[30.09090909]])

Empty DataFrame
Columns: []
Index: []

i: 


46

y: 


array([[31],
       [30],
       [29],
       [29]])

x: 


array([[45],
       [46],
       [46],
       [47]])

array([[29.75]])

Empty DataFrame
Columns: []
Index: []

i: 


47

y: 


array([[30],
       [29],
       [29],
       [29]])

x: 


array([[46],
       [46],
       [47],
       [48]])

array([[29.18181818]])

Empty DataFrame
Columns: []
Index: []

i: 


48

y: 


array([[29],
       [29],
       [31],
       [29]])

x: 


array([[47],
       [48],
       [49],
       [49]])

array([[29.36363636]])

Empty DataFrame
Columns: []
Index: []

i: 


49

y: 


array([[29],
       [31],
       [29],
       [32],
       [31]])

x: 


array([[48],
       [49],
       [49],
       [50],
       [50]])

array([[30.14285714]])

Empty DataFrame
Columns: []
Index: []

i: 


50

y: 


array([[31],
       [29],
       [32],
       [31],
       [30]])

x: 


array([[49],
       [49],
       [50],
       [50],
       [51]])

array([[30.64285714]])

Empty DataFrame
Columns: []
Index: []

i: 


51

y: 


array([[32],
       [31],
       [30]])

x: 


array([[50],
       [50],
       [51]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


52

y: 


array([[30]])

x: 


array([[51]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


53

y: 


array([[28],
       [30]])

x: 


array([[54],
       [54]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


54

y: 


array([[28],
       [30]])

x: 


array([[54],
       [54]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


55

y: 


array([[28],
       [30],
       [29]])

x: 


array([[54],
       [54],
       [56]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


56

y: 


array([[29]])

x: 


array([[56]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


57

y: 


array([[29],
       [31],
       [32]])

x: 


array([[56],
       [58],
       [58]])

array([[30.25]])

Empty DataFrame
Columns: []
Index: []

i: 


58

y: 


array([[31],
       [32]])

x: 


array([[58],
       [58]])

array([[31.5]])

Empty DataFrame
Columns: []
Index: []

i: 


59

y: 


array([[31],
       [32]])

x: 


array([[58],
       [58]])

array([[31.5]])

Empty DataFrame
Columns: []
Index: []

i: 


60

y: 


array([[31]])

x: 


array([[61]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


61

y: 


array([[31]])

x: 


array([[61]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


62

y: 


array([[31],
       [30]])

x: 


array([[61],
       [63]])

array([[30.5]])

Empty DataFrame
Columns: []
Index: []

i: 


63

y: 


array([[30],
       [30]])

x: 


array([[63],
       [64]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


64

y: 


array([[30],
       [30]])

x: 


array([[63],
       [64]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


65

y: 


array([[30]])

x: 


array([[64]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


67

y: 


array([[32],
       [29]])

x: 


array([[68],
       [68]])

array([[30.5]])

Empty DataFrame
Columns: []
Index: []

i: 


68

y: 


array([[32],
       [29]])

x: 


array([[68],
       [68]])

array([[30.5]])

Empty DataFrame
Columns: []
Index: []

i: 


69

y: 


array([[32],
       [29],
       [29]])

x: 


array([[68],
       [68],
       [70]])

array([[29.75]])

Empty DataFrame
Columns: []
Index: []

i: 


70

y: 


array([[29]])

x: 


array([[70]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


71

y: 


array([[29],
       [27]])

x: 


array([[70],
       [72]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


72

y: 


array([[27]])

x: 


array([[72]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


73

y: 


array([[27],
       [31]])

x: 


array([[72],
       [74]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


74

y: 


array([[31],
       [30],
       [28]])

x: 


array([[74],
       [75],
       [75]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


75

y: 


array([[31],
       [30],
       [28]])

x: 


array([[74],
       [75],
       [75]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


76

y: 


array([[30],
       [28],
       [27]])

x: 


array([[75],
       [75],
       [77]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


77

y: 


array([[27]])

x: 


array([[77]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


78

y: 


array([[27]])

x: 


array([[77]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


81

y: 


array([[29]])

x: 


array([[82]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


82

y: 


array([[29],
       [28],
       [29],
       [28]])

x: 


array([[82],
       [83],
       [83],
       [83]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


83

y: 


array([[29],
       [28],
       [29],
       [28],
       [26]])

x: 


array([[82],
       [83],
       [83],
       [83],
       [84]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


84

y: 


array([[28],
       [29],
       [28],
       [26]])

x: 


array([[83],
       [83],
       [83],
       [84]])

array([[26.]])

Empty DataFrame
Columns: []
Index: []

i: 


85

y: 


array([[26],
       [28]])

x: 


array([[84],
       [86]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


86

y: 


array([[28]])

x: 


array([[86]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


87

y: 


array([[28]])

x: 


array([[86]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


88

y: 


array([[26]])

x: 


array([[89]])

array([[26.]])

Empty DataFrame
Columns: []
Index: []

i: 


89

y: 


array([[26],
       [25]])

x: 


array([[89],
       [90]])

array([[26.]])

Empty DataFrame
Columns: []
Index: []

i: 


90

y: 


array([[26],
       [25],
       [28],
       [28],
       [29]])

x: 


array([[89],
       [90],
       [91],
       [91],
       [91]])

array([[26.625]])

Empty DataFrame
Columns: []
Index: []

i: 


91

y: 


array([[25],
       [28],
       [28],
       [29],
       [29]])

x: 


array([[90],
       [91],
       [91],
       [91],
       [92]])

array([[27.8]])

Empty DataFrame
Columns: []
Index: []

i: 


92

y: 


array([[28],
       [28],
       [29],
       [29],
       [28]])

x: 


array([[91],
       [91],
       [91],
       [92],
       [93]])

array([[28.375]])

Empty DataFrame
Columns: []
Index: []

i: 


93

y: 


array([[29],
       [28]])

x: 


array([[92],
       [93]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


94

y: 


array([[28]])

x: 


array([[93]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


95

y: 


array([[29]])

x: 


array([[96]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


96

y: 


array([[29],
       [27]])

x: 


array([[96],
       [97]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


97

y: 


array([[29],
       [27],
       [27],
       [27]])

x: 


array([[96],
       [97],
       [98],
       [98]])

array([[27.72727273]])

Empty DataFrame
Columns: []
Index: []

i: 


98

y: 


array([[27],
       [27],
       [27]])

x: 


array([[97],
       [98],
       [98]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


99

y: 


array([[27],
       [27]])

x: 


array([[98],
       [98]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


101

y: 


array([[28]])

x: 


array([[102]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


102

y: 


array([[28],
       [27]])

x: 


array([[102],
       [103]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


103

y: 


array([[28],
       [27],
       [25],
       [28],
       [26],
       [28]])

x: 


array([[102],
       [103],
       [104],
       [104],
       [104],
       [104]])

array([[27.28571429]])

Empty DataFrame
Columns: []
Index: []

i: 


104

y: 


array([[27],
       [25],
       [28],
       [26],
       [28],
       [25]])

x: 


array([[103],
       [104],
       [104],
       [104],
       [104],
       [105]])

array([[26.5]])

Empty DataFrame
Columns: []
Index: []

i: 


105

y: 


array([[25],
       [28],
       [26],
       [28],
       [25]])

x: 


array([[104],
       [104],
       [104],
       [104],
       [105]])

array([[25.]])

Empty DataFrame
Columns: []
Index: []

i: 


106

y: 


array([[25]])

x: 


array([[105]])

array([[25.]])

Empty DataFrame
Columns: []
Index: []

i: 


109

y: 


array([[30]])

x: 


array([[110]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


110

y: 


array([[30],
       [29]])

x: 


array([[110],
       [111]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


111

y: 


array([[30],
       [29],
       [29]])

x: 


array([[110],
       [111],
       [112]])

array([[29.33333333]])

Empty DataFrame
Columns: []
Index: []

i: 


112

y: 


array([[29],
       [29]])

x: 


array([[111],
       [112]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


113

y: 


array([[29]])

x: 


array([[112]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


115

y: 


array([[30],
       [29]])

x: 


array([[116],
       [116]])

array([[29.5]])

Empty DataFrame
Columns: []
Index: []

i: 


116

y: 


array([[30],
       [29],
       [30]])

x: 


array([[116],
       [116],
       [117]])

array([[29.5]])

Empty DataFrame
Columns: []
Index: []

i: 


117

y: 


array([[30],
       [29],
       [30]])

x: 


array([[116],
       [116],
       [117]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


118

y: 


array([[30],
       [31],
       [27]])

x: 


array([[117],
       [119],
       [119]])

array([[29.5]])

Empty DataFrame
Columns: []
Index: []

i: 


119

y: 


array([[31],
       [27]])

x: 


array([[119],
       [119]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


120

y: 


array([[31],
       [27]])

x: 


array([[119],
       [119]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


123

y: 


array([[27]])

x: 


array([[124]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


124

y: 


array([[27]])

x: 


array([[124]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


125

y: 


array([[27],
       [29]])

x: 


array([[124],
       [126]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


126

y: 


array([[29],
       [28]])

x: 


array([[126],
       [127]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


127

y: 


array([[29],
       [28]])

x: 


array([[126],
       [127]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


128

y: 


array([[28]])

x: 


array([[127]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


129

y: 


array([[30]])

x: 


array([[130]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


130

y: 


array([[30],
       [29]])

x: 


array([[130],
       [131]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


131

y: 


array([[30],
       [29]])

x: 


array([[130],
       [131]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


132

y: 


array([[29],
       [30]])

x: 


array([[131],
       [133]])

array([[29.5]])

Empty DataFrame
Columns: []
Index: []

i: 


133

y: 


array([[30]])

x: 


array([[133]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


134

y: 


array([[30]])

x: 


array([[133]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


135

y: 


array([[28]])

x: 


array([[136]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


136

y: 


array([[28]])

x: 


array([[136]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


137

y: 


array([[28]])

x: 


array([[136]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


140

y: 


array([[29]])

x: 


array([[141]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


141

y: 


array([[29],
       [29]])

x: 


array([[141],
       [142]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


142

y: 


array([[29],
       [29]])

x: 


array([[141],
       [142]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


143

y: 


array([[29]])

x: 


array([[142]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


144

y: 


array([[28]])

x: 


array([[145]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


145

y: 


array([[28],
       [28]])

x: 


array([[145],
       [146]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


146

y: 


array([[28],
       [28]])

x: 


array([[145],
       [146]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


147

y: 


array([[28]])

x: 


array([[146]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


151

y: 


array([[30]])

x: 


array([[152]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


152

y: 


array([[30]])

x: 


array([[152]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


153

y: 


array([[30]])

x: 


array([[152]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


155

y: 


array([[27],
       [27]])

x: 


array([[156],
       [156]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


156

y: 


array([[27],
       [27]])

x: 


array([[156],
       [156]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


157

y: 


array([[27],
       [27]])

x: 


array([[156],
       [156]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


158

y: 


array([[28]])

x: 


array([[159]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


159

y: 


array([[28]])

x: 


array([[159]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


160

y: 


array([[28]])

x: 


array([[159]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


161

y: 


array([[28]])

x: 


array([[162]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


162

y: 


array([[28]])

x: 


array([[162]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


163

y: 


array([[28]])

x: 


array([[162]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


165

y: 


array([[27]])

x: 


array([[166]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


166

y: 


array([[27],
       [28]])

x: 


array([[166],
       [167]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


167

y: 


array([[27],
       [28],
       [31],
       [26]])

x: 


array([[166],
       [167],
       [168],
       [168]])

array([[27.81818182]])

Empty DataFrame
Columns: []
Index: []

i: 


168

y: 


array([[28],
       [31],
       [26]])

x: 


array([[167],
       [168],
       [168]])

array([[28.5]])

Empty DataFrame
Columns: []
Index: []

i: 


169

y: 


array([[31],
       [26]])

x: 


array([[168],
       [168]])

array([[28.5]])

Empty DataFrame
Columns: []
Index: []

i: 


180

y: 


array([[29]])

x: 


array([[181]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


181

y: 


array([[29]])

x: 


array([[181]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


182

y: 


array([[29]])

x: 


array([[181]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


187

y: 


array([[30],
       [30]])

x: 


array([[188],
       [188]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


188

y: 


array([[30],
       [30]])

x: 


array([[188],
       [188]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


189

y: 


array([[30],
       [30]])

x: 


array([[188],
       [188]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


191

y: 


array([[30]])

x: 


array([[192]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


192

y: 


array([[30],
       [31]])

x: 


array([[192],
       [193]])

array([[30.]])

Empty DataFrame
Columns: []
Index: []

i: 


193

y: 


array([[30],
       [31]])

x: 


array([[192],
       [193]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


194

y: 


array([[31]])

x: 


array([[193]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


196

y: 


array([[31]])

x: 


array([[197]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


197

y: 


array([[31]])

x: 


array([[197]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


198

y: 


array([[31]])

x: 


array([[197]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


199

y: 


array([[31]])

x: 


array([[200]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


200

y: 


array([[31]])

x: 


array([[200]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


201

y: 


array([[31]])

x: 


array([[200]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


207

y: 


array([[28]])

x: 


array([[208]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


208

y: 


array([[28]])

x: 


array([[208]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


209

y: 


array([[28]])

x: 


array([[208]])

array([[28.]])

Empty DataFrame
Columns: []
Index: []

i: 


211

y: 


array([[31]])

x: 


array([[212]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


212

y: 


array([[31]])

x: 


array([[212]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


213

y: 


array([[31],
       [32]])

x: 


array([[212],
       [214]])

array([[31.5]])

Empty DataFrame
Columns: []
Index: []

i: 


214

y: 


array([[32],
       [31]])

x: 


array([[214],
       [215]])

array([[32.]])

Empty DataFrame
Columns: []
Index: []

i: 


215

y: 


array([[32],
       [31],
       [29]])

x: 


array([[214],
       [215],
       [216]])

array([[30.66666667]])

Empty DataFrame
Columns: []
Index: []

i: 


216

y: 


array([[31],
       [29]])

x: 


array([[215],
       [216]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


217

y: 


array([[29]])

x: 


array([[216]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


218

y: 


array([[33],
       [30]])

x: 


array([[219],
       [219]])

array([[31.5]])

Empty DataFrame
Columns: []
Index: []

i: 


219

y: 


array([[33],
       [30]])

x: 


array([[219],
       [219]])

array([[31.5]])

Empty DataFrame
Columns: []
Index: []

i: 


220

y: 


array([[33],
       [30]])

x: 


array([[219],
       [219]])

array([[31.5]])

Empty DataFrame
Columns: []
Index: []

i: 


221

y: 


array([[27]])

x: 


array([[222]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


222

y: 


array([[27],
       [32]])

x: 


array([[222],
       [223]])

array([[27.]])

Empty DataFrame
Columns: []
Index: []

i: 


223

y: 


array([[27],
       [32]])

x: 


array([[222],
       [223]])

array([[32.]])

Empty DataFrame
Columns: []
Index: []

i: 


224

y: 


array([[32],
       [29]])

x: 


array([[223],
       [225]])

array([[30.5]])

Empty DataFrame
Columns: []
Index: []

i: 


225

y: 


array([[29]])

x: 


array([[225]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


226

y: 


array([[29]])

x: 


array([[225]])

array([[29.]])

Empty DataFrame
Columns: []
Index: []

i: 


227

y: 


array([[31]])

x: 


array([[228]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


228

y: 


array([[31],
       [29],
       [30]])

x: 


array([[228],
       [229],
       [229]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


229

y: 


array([[31],
       [29],
       [30],
       [32]])

x: 


array([[228],
       [229],
       [229],
       [230]])

array([[30.5]])

Empty DataFrame
Columns: []
Index: []

i: 


230

y: 


array([[29],
       [30],
       [32],
       [35]])

x: 


array([[229],
       [229],
       [230],
       [231]])

array([[32.18181818]])

Empty DataFrame
Columns: []
Index: []

i: 


231

y: 


array([[32],
       [35]])

x: 


array([[230],
       [231]])

array([[35.]])

Empty DataFrame
Columns: []
Index: []

i: 


232

y: 


array([[35]])

x: 


array([[231]])

array([[35.]])

Empty DataFrame
Columns: []
Index: []

i: 


235

y: 


array([[33]])

x: 


array([[236]])

array([[33.]])

Empty DataFrame
Columns: []
Index: []

i: 


236

y: 


array([[33]])

x: 


array([[236]])

array([[33.]])

Empty DataFrame
Columns: []
Index: []

i: 


237

y: 


array([[33],
       [31]])

x: 


array([[236],
       [238]])

array([[32.]])

Empty DataFrame
Columns: []
Index: []

i: 


238

y: 


array([[31]])

x: 


array([[238]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


239

y: 


array([[31]])

x: 


array([[238]])

array([[31.]])

Empty DataFrame
Columns: []
Index: []

i: 


242

y: 


array([[31],
       [32]])

x: 


array([[243],
       [243]])

array([[31.5]])

Empty DataFrame
Columns: []
Index: []

i: 


243

y: 


array([[31],
       [32],
       [32],
       [35],
       [35]])

x: 


array([[243],
       [243],
       [244],
       [244],
       [244]])

array([[31.5]])

Empty DataFrame
Columns: []
Index: []

i: 


244

y: 


array([[31],
       [32],
       [32],
       [35],
       [35]])

x: 


array([[243],
       [243],
       [244],
       [244],
       [244]])

array([[34.]])

Empty DataFrame
Columns: []
Index: []

i: 


245

y: 


array([[32],
       [35],
       [35]])

x: 


array([[244],
       [244],
       [244]])

array([[34.]])

Empty DataFrame
Columns: []
Index: []

i: 


251

y: 


array([[34]])

x: 


array([[252]])

array([[34.]])

Empty DataFrame
Columns: []
Index: []

i: 


252

y: 


array([[34]])

x: 


array([[252]])

array([[34.]])

Empty DataFrame
Columns: []
Index: []

i: 


253

y: 


array([[34],
       [33]])

x: 


array([[252],
       [254]])

array([[33.5]])

Empty DataFrame
Columns: []
Index: []

i: 


254

y: 


array([[33]])

x: 


array([[254]])

array([[33.]])

Empty DataFrame
Columns: []
Index: []

i: 


255

y: 


array([[33]])

x: 


array([[254]])

array([[33.]])

Empty DataFrame
Columns: []
Index: []

i: 


256

y: 


array([[36]])

x: 


array([[257]])

array([[36.]])

Empty DataFrame
Columns: []
Index: []

i: 


257

y: 


array([[36],
       [36]])

x: 


array([[257],
       [258]])

array([[36.]])

Empty DataFrame
Columns: []
Index: []

i: 


258

y: 


array([[36],
       [36]])

x: 


array([[257],
       [258]])

array([[36.]])

Empty DataFrame
Columns: []
Index: []

i: 


259

y: 


array([[36],
       [37]])

x: 


array([[258],
       [260]])

array([[36.5]])

Empty DataFrame
Columns: []
Index: []

i: 


260

y: 


array([[37]])

x: 


array([[260]])

array([[37.]])

Empty DataFrame
Columns: []
Index: []

i: 


261

y: 


array([[37]])

x: 


array([[260]])

array([[37.]])

Empty DataFrame
Columns: []
Index: []

i: 


262

y: 


array([[38]])

x: 


array([[263]])

array([[38.]])

Empty DataFrame
Columns: []
Index: []

i: 


263

y: 


array([[38]])

x: 


array([[263]])

array([[38.]])

Empty DataFrame
Columns: []
Index: []

i: 


264

y: 


array([[38]])

x: 


array([[263]])

array([[38.]])

Empty DataFrame
Columns: []
Index: []

i: 


267

y: 


array([[38]])

x: 


array([[268]])

array([[38.]])

Empty DataFrame
Columns: []
Index: []

i: 


268

y: 


array([[38]])

x: 


array([[268]])

array([[38.]])

Empty DataFrame
Columns: []
Index: []

i: 


269

y: 


array([[38]])

x: 


array([[268]])

array([[38.]])

Empty DataFrame
Columns: []
Index: []

i: 


278

y: 


array([[41],
       [41]])

x: 


array([[279],
       [279]])

array([[41.]])

Empty DataFrame
Columns: []
Index: []

i: 


279

y: 


array([[41],
       [41]])

x: 


array([[279],
       [279]])

array([[41.]])

Empty DataFrame
Columns: []
Index: []

i: 


280

y: 


array([[41],
       [41]])

x: 


array([[279],
       [279]])

array([[41.]])

Empty DataFrame
Columns: []
Index: []

i: 


284

y: 


array([[41]])

x: 


array([[285]])

array([[41.]])

Empty DataFrame
Columns: []
Index: []

i: 


285

y: 


array([[41]])

x: 


array([[285]])

array([[41.]])

Empty DataFrame
Columns: []
Index: []

i: 


286

y: 


array([[41]])

x: 


array([[285]])

array([[41.]])

Empty DataFrame
Columns: []
Index: []

i: 


287

y: 


array([[40]])

x: 


array([[288]])

array([[40.]])

Empty DataFrame
Columns: []
Index: []

i: 


288

y: 


array([[40]])

x: 


array([[288]])

array([[40.]])

Empty DataFrame
Columns: []
Index: []

i: 


289

y: 


array([[40]])

x: 


array([[288]])

array([[40.]])

Empty DataFrame
Columns: []
Index: []

i: 


300

y: 


array([[41]])

x: 


array([[301]])

array([[41.]])

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Defining the LOWESS function

In [ ]:
delta=3
length = just_polls['Days Before election'].max()
indeces = just_polls['Days Before election']
delta = delta/2
loess_data = zeroes
  #frame is the pandas dataframe, range is the delta of spread. higher delta means more days. length is the total number of days before an election since this assumes some polls may overlap.

for i in range(length):
  temp_frame  = just_polls;
  for column in just_polls[2:]:
    temp_frame[column, just_polls['Days Before Election']>i - delta and just_polls['Days Before Election'] < i+delta ]



NameError: ignored

In [ ]:
#[:,-1] rows and columns

just_polls_parties = just_polls.iloc[:, 0:13]
just_polls_blocks = just_polls.iloc[:,14:18]
just_polls_blocks.plot(figsize=(20, 30, ), style =".")

#You pass the wanted axis to the ax argument
df.plot(kind='scatter', x='x', y='y',title="Nice title", grid=True,fontsize=10, ax=ax) 
ax.plot(line, x_line, zorder=-1)

In [ ]:
#Loess and lowess

for i in range(length(just_polls))
  display(i)

In [ ]:
covariance = just_polls.corr()
print("covariance")
display(covariance)
heat_map = sea.heatmap(df.corr(), covariance,annot=True, cmap = "RdBu")
plt.figure(figsize = (30,15))
sea.heatmap()

In [ ]:
correlation_3_day = pd.read_excel(data, sheet_name=1, index_col=0)
display(correlation_3_day)

3 day rolling average

In [ ]:
correlation_3_day = correlation_3_day.iloc[1:159, 25:35]
display(correlation_3_day)


In [ ]:
correlation_3_poll = pd.read_excel(data, sheet_name=2, index_col=0)
correlation_3_poll = correlation_3_poll.iloc[444:454, 1:19]

heat_map2 = sea.heatmap(correlation_3_day, annot=True, cmap = "RdBu");
plt.show()
heat_map3 = sea.heatmap(correlation_3_poll, annot=True, cmap = "RdBu");
plt.show()
# temp = just_polls[1:1, 1:1]
# start, stop =1;
stm.nonparametric.lowess()


